addSbtPlugin("io.spray"         % "sbt-revolver"          % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"   % "1.3.5")
addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"  % "0.9.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.3.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.4.0")
